// TypeScript wrapper to interact with the C++ WebAssembly module

export interface InitOptions {
    canvasId: string;
    width?: number;
    height?: number;
}

export class NexusCharts {
    private canvas: HTMLCanvasElement | null = null;
    private moduleLoaded: boolean = false;

    constructor(options: InitOptions) {
        this.canvas = document.getElementById(options.canvasId) as HTMLCanvasElement;

        if (!this.canvas) {
            console.error(`[NexusCharts] Canvas with ID '${options.canvasId}' not found!`);
            return;
        }

        if (options.width) this.canvas.width = options.width;
        if (options.height) this.canvas.height = options.height;

        this.initEngine();
    }

    private initEngine() {
        // Here we will load the WebAssembly module generated by Emscripten
        console.log("[NexusCharts:JS] Initializing WASM module...");

        // This is a placeholder for the actual Emscripten module loader
        // In a real scenario, we would await the Module promise and then call Module.initEngine()
        setTimeout(() => {
            console.log("[NexusCharts:JS] WASM module loaded (Mock).");
            this.moduleLoaded = true;
        }, 500);
    }

    public isReady(): boolean {
        return this.moduleLoaded;
    }
}
